### ISSUE TITLE
is it possible to show multiple column with horizonal scroll?

### ISSUE THREAD

**Issue by karthisiva** [devedbox/AXAttributedLabel#1]
I will get html string form server, then i want to place it and needs to show like a news paper.

**Comment by devedbox** [comment]
Sorry. `AXAttributedLabel` won't support the scroll because the aim is designed to work like the `UILabel` with attributed text. But, you can get a [fork](https://github.com/devedbox/AXAttributedLabel/issues/1#fork-destination-box) to add the feature and putting me a `pr` will be helpful.
